apiVersion: v1
kind: Service
metadata:
  name: data-procesing-service
  namespace: data-processor-ns
  labels:
    app: data-proc-service
    tier: data-processing
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
  selector:
    app: data-processing-tier
    tier: data-processing
